[2023-06-17T05:51:27.746+0000] {processor.py:157} INFO - Started process (PID=110) to work on /opt/airflow/dags/transform.py
[2023-06-17T05:51:27.749+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2023-06-17T05:51:27.752+0000] {logging_mixin.py:149} INFO - [2023-06-17T05:51:27.751+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2023-06-17T05:51:27.954+0000] {logging_mixin.py:149} INFO - [2023-06-17T05:51:27.830+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 12, in <module>
    "email_on_failaure": false,
NameError: name 'false' is not defined
[2023-06-17T05:51:27.955+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2023-06-17T05:51:28.112+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transform.py took 0.383 seconds
[2023-06-17T05:51:59.923+0000] {processor.py:157} INFO - Started process (PID=176) to work on /opt/airflow/dags/transform.py
[2023-06-17T05:51:59.965+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2023-06-17T05:51:59.967+0000] {logging_mixin.py:149} INFO - [2023-06-17T05:51:59.966+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2023-06-17T05:51:59.972+0000] {logging_mixin.py:149} INFO - [2023-06-17T05:51:59.970+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 12, in <module>
    "email_on_failaure": false,
NameError: name 'false' is not defined
[2023-06-17T05:51:59.973+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2023-06-17T05:52:00.062+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transform.py took 0.145 seconds
[2023-06-17T05:52:34.312+0000] {processor.py:157} INFO - Started process (PID=238) to work on /opt/airflow/dags/transform.py
[2023-06-17T05:52:34.313+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2023-06-17T05:52:34.314+0000] {logging_mixin.py:149} INFO - [2023-06-17T05:52:34.314+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2023-06-17T05:52:34.317+0000] {logging_mixin.py:149} INFO - [2023-06-17T05:52:34.316+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 12, in <module>
    "email_on_failaure": false,
NameError: name 'false' is not defined
[2023-06-17T05:52:34.318+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2023-06-17T05:52:34.368+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transform.py took 0.060 seconds
[2023-06-17T05:53:04.895+0000] {processor.py:157} INFO - Started process (PID=308) to work on /opt/airflow/dags/transform.py
[2023-06-17T05:53:04.896+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2023-06-17T05:53:04.897+0000] {logging_mixin.py:149} INFO - [2023-06-17T05:53:04.896+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2023-06-17T05:53:04.900+0000] {logging_mixin.py:149} INFO - [2023-06-17T05:53:04.899+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 12, in <module>
    "email_on_failaure": false,
NameError: name 'false' is not defined
[2023-06-17T05:53:04.900+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2023-06-17T05:53:04.935+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transform.py took 0.044 seconds
[2023-06-17T05:53:36.435+0000] {processor.py:157} INFO - Started process (PID=385) to work on /opt/airflow/dags/transform.py
[2023-06-17T05:53:36.527+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2023-06-17T05:53:36.529+0000] {logging_mixin.py:149} INFO - [2023-06-17T05:53:36.528+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2023-06-17T05:53:36.539+0000] {logging_mixin.py:149} INFO - [2023-06-17T05:53:36.535+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 12, in <module>
    "email_on_failaure": false,
NameError: name 'false' is not defined
[2023-06-17T05:53:36.541+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2023-06-17T05:53:36.672+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transform.py took 0.241 seconds
[2023-06-17T05:54:07.295+0000] {processor.py:157} INFO - Started process (PID=453) to work on /opt/airflow/dags/transform.py
[2023-06-17T05:54:07.308+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2023-06-17T05:54:07.309+0000] {logging_mixin.py:149} INFO - [2023-06-17T05:54:07.308+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2023-06-17T05:54:07.312+0000] {logging_mixin.py:149} INFO - [2023-06-17T05:54:07.311+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 12, in <module>
    "email_on_failaure": false,
NameError: name 'false' is not defined
[2023-06-17T05:54:07.312+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2023-06-17T05:54:07.365+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transform.py took 0.075 seconds
[2023-06-17T05:55:04.188+0000] {processor.py:157} INFO - Started process (PID=528) to work on /opt/airflow/dags/transform.py
[2023-06-17T05:55:04.261+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2023-06-17T05:55:04.263+0000] {logging_mixin.py:149} INFO - [2023-06-17T05:55:04.262+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2023-06-17T05:55:04.291+0000] {logging_mixin.py:149} INFO - [2023-06-17T05:55:04.289+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 12, in <module>
    "email_on_failaure": false,
NameError: name 'false' is not defined
[2023-06-17T05:55:04.292+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2023-06-17T05:55:04.409+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transform.py took 0.227 seconds
[2023-06-17T05:55:35.500+0000] {processor.py:157} INFO - Started process (PID=596) to work on /opt/airflow/dags/transform.py
[2023-06-17T05:55:35.583+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2023-06-17T05:55:35.584+0000] {logging_mixin.py:149} INFO - [2023-06-17T05:55:35.584+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2023-06-17T05:55:35.590+0000] {logging_mixin.py:149} INFO - [2023-06-17T05:55:35.588+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 12, in <module>
    "email_on_failaure": false,
NameError: name 'false' is not defined
[2023-06-17T05:55:35.591+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2023-06-17T05:55:35.697+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transform.py took 0.201 seconds
[2023-06-17T05:56:06.231+0000] {processor.py:157} INFO - Started process (PID=659) to work on /opt/airflow/dags/transform.py
[2023-06-17T05:56:06.232+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2023-06-17T05:56:06.233+0000] {logging_mixin.py:149} INFO - [2023-06-17T05:56:06.233+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2023-06-17T05:56:06.236+0000] {logging_mixin.py:149} INFO - [2023-06-17T05:56:06.234+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 12, in <module>
    "email_on_failaure": false,
NameError: name 'false' is not defined
[2023-06-17T05:56:06.236+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2023-06-17T05:56:06.288+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transform.py took 0.060 seconds
[2023-06-17T14:09:58.750+0000] {processor.py:157} INFO - Started process (PID=119) to work on /opt/airflow/dags/transform.py
[2023-06-17T14:09:58.781+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2023-06-17T14:09:58.782+0000] {logging_mixin.py:149} INFO - [2023-06-17T14:09:58.782+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2023-06-17T14:09:58.857+0000] {logging_mixin.py:149} INFO - [2023-06-17T14:09:58.853+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 12, in <module>
    "email_on_failaure": false,
NameError: name 'false' is not defined
[2023-06-17T14:09:58.859+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2023-06-17T14:09:59.032+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transform.py took 0.287 seconds
[2023-06-17T14:16:23.153+0000] {processor.py:157} INFO - Started process (PID=120) to work on /opt/airflow/dags/transform.py
[2023-06-17T14:16:23.259+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2023-06-17T14:16:23.262+0000] {logging_mixin.py:149} INFO - [2023-06-17T14:16:23.261+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2023-06-17T14:16:23.513+0000] {logging_mixin.py:149} INFO - [2023-06-17T14:16:23.378+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 12, in <module>
    "email_on_failaure": false,
NameError: name 'false' is not defined
[2023-06-17T14:16:23.514+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2023-06-17T14:16:23.637+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transform.py took 0.488 seconds
[2023-06-17T14:16:53.826+0000] {processor.py:157} INFO - Started process (PID=184) to work on /opt/airflow/dags/transform.py
[2023-06-17T14:16:53.827+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2023-06-17T14:16:53.828+0000] {logging_mixin.py:149} INFO - [2023-06-17T14:16:53.828+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2023-06-17T14:16:53.832+0000] {logging_mixin.py:149} INFO - [2023-06-17T14:16:53.831+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 12, in <module>
    "email_on_failaure": false,
NameError: name 'false' is not defined
[2023-06-17T14:16:53.832+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2023-06-17T14:16:53.874+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transform.py took 0.053 seconds
