[2023-06-18T09:51:33.205+0000] {processor.py:157} INFO - Started process (PID=119) to work on /opt/airflow/dags/transform.py
[2023-06-18T09:51:33.206+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2023-06-18T09:51:33.207+0000] {logging_mixin.py:149} INFO - [2023-06-18T09:51:33.206+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2023-06-18T09:51:33.244+0000] {logging_mixin.py:149} INFO - [2023-06-18T09:51:33.242+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 12, in <module>
    "email_on_failaure": false,
NameError: name 'false' is not defined
[2023-06-18T09:51:33.245+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2023-06-18T09:51:33.539+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transform.py took 0.338 seconds
[2023-06-18T09:54:01.327+0000] {processor.py:157} INFO - Started process (PID=223) to work on /opt/airflow/dags/transform.py
[2023-06-18T09:54:01.441+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2023-06-18T09:54:01.444+0000] {logging_mixin.py:149} INFO - [2023-06-18T09:54:01.443+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2023-06-18T09:54:01.493+0000] {logging_mixin.py:149} INFO - [2023-06-18T09:54:01.489+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 12, in <module>
    "email_on_failaure": false,
NameError: name 'false' is not defined
[2023-06-18T09:54:01.495+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2023-06-18T09:54:01.731+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transform.py took 0.434 seconds
[2023-06-18T09:54:33.084+0000] {processor.py:157} INFO - Started process (PID=290) to work on /opt/airflow/dags/transform.py
[2023-06-18T09:54:33.106+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2023-06-18T09:54:33.108+0000] {logging_mixin.py:149} INFO - [2023-06-18T09:54:33.107+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2023-06-18T09:54:33.116+0000] {logging_mixin.py:149} INFO - [2023-06-18T09:54:33.113+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 12, in <module>
    "email_on_failaure": false,
NameError: name 'false' is not defined
[2023-06-18T09:54:33.117+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2023-06-18T09:54:33.175+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transform.py took 0.095 seconds
[2023-06-18T09:55:04.952+0000] {processor.py:157} INFO - Started process (PID=360) to work on /opt/airflow/dags/transform.py
[2023-06-18T09:55:04.980+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2023-06-18T09:55:04.981+0000] {logging_mixin.py:149} INFO - [2023-06-18T09:55:04.981+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2023-06-18T09:55:04.984+0000] {logging_mixin.py:149} INFO - [2023-06-18T09:55:04.983+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 12, in <module>
    "email_on_failaure": false,
NameError: name 'false' is not defined
[2023-06-18T09:55:04.985+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2023-06-18T09:55:05.028+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transform.py took 0.081 seconds
[2023-06-18T09:55:40.474+0000] {processor.py:157} INFO - Started process (PID=445) to work on /opt/airflow/dags/transform.py
[2023-06-18T09:55:40.476+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2023-06-18T09:55:40.477+0000] {logging_mixin.py:149} INFO - [2023-06-18T09:55:40.477+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2023-06-18T09:55:40.481+0000] {logging_mixin.py:149} INFO - [2023-06-18T09:55:40.480+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 12, in <module>
    "email_on_failaure": false,
NameError: name 'false' is not defined
[2023-06-18T09:55:40.482+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2023-06-18T09:55:40.535+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transform.py took 0.067 seconds
[2023-06-18T09:56:10.858+0000] {processor.py:157} INFO - Started process (PID=513) to work on /opt/airflow/dags/transform.py
[2023-06-18T09:56:10.860+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2023-06-18T09:56:10.860+0000] {logging_mixin.py:149} INFO - [2023-06-18T09:56:10.860+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2023-06-18T09:56:10.864+0000] {logging_mixin.py:149} INFO - [2023-06-18T09:56:10.863+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 12, in <module>
    "email_on_failaure": false,
NameError: name 'false' is not defined
[2023-06-18T09:56:10.864+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2023-06-18T09:56:10.895+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transform.py took 0.042 seconds
