[2023-06-16T00:40:13.917+0000] {processor.py:157} INFO - Started process (PID=143) to work on /opt/airflow/dags/transform.py
[2023-06-16T00:40:13.919+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2023-06-16T00:40:13.922+0000] {logging_mixin.py:149} INFO - [2023-06-16T00:40:13.921+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2023-06-16T00:40:13.986+0000] {logging_mixin.py:149} INFO - [2023-06-16T00:40:13.984+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 12, in <module>
    "email_on_failaure": false,
NameError: name 'false' is not defined
[2023-06-16T00:40:13.986+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2023-06-16T00:40:14.111+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transform.py took 0.210 seconds
[2023-06-16T00:42:10.369+0000] {processor.py:157} INFO - Started process (PID=255) to work on /opt/airflow/dags/transform.py
[2023-06-16T00:42:10.370+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2023-06-16T00:42:10.371+0000] {logging_mixin.py:149} INFO - [2023-06-16T00:42:10.371+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2023-06-16T00:42:10.402+0000] {logging_mixin.py:149} INFO - [2023-06-16T00:42:10.400+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 12, in <module>
    "email_on_failaure": false,
NameError: name 'false' is not defined
[2023-06-16T00:42:10.402+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2023-06-16T00:42:10.440+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transform.py took 0.075 seconds
[2023-06-16T00:42:40.752+0000] {processor.py:157} INFO - Started process (PID=319) to work on /opt/airflow/dags/transform.py
[2023-06-16T00:42:40.754+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2023-06-16T00:42:40.755+0000] {logging_mixin.py:149} INFO - [2023-06-16T00:42:40.755+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2023-06-16T00:42:40.761+0000] {logging_mixin.py:149} INFO - [2023-06-16T00:42:40.758+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 12, in <module>
    "email_on_failaure": false,
NameError: name 'false' is not defined
[2023-06-16T00:42:40.762+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2023-06-16T00:42:40.940+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transform.py took 0.195 seconds
[2023-06-16T00:43:22.174+0000] {processor.py:157} INFO - Started process (PID=394) to work on /opt/airflow/dags/transform.py
[2023-06-16T00:43:22.175+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2023-06-16T00:43:22.176+0000] {logging_mixin.py:149} INFO - [2023-06-16T00:43:22.176+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2023-06-16T00:43:22.494+0000] {logging_mixin.py:149} INFO - [2023-06-16T00:43:22.179+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 12, in <module>
    "email_on_failaure": false,
NameError: name 'false' is not defined
[2023-06-16T00:43:22.495+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2023-06-16T00:43:22.609+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transform.py took 0.440 seconds
[2023-06-16T00:43:53.460+0000] {processor.py:157} INFO - Started process (PID=455) to work on /opt/airflow/dags/transform.py
[2023-06-16T00:43:53.461+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2023-06-16T00:43:53.462+0000] {logging_mixin.py:149} INFO - [2023-06-16T00:43:53.462+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2023-06-16T00:43:53.465+0000] {logging_mixin.py:149} INFO - [2023-06-16T00:43:53.464+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 12, in <module>
    "email_on_failaure": false,
NameError: name 'false' is not defined
[2023-06-16T00:43:53.465+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2023-06-16T00:43:53.596+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transform.py took 0.141 seconds
[2023-06-16T00:44:54.798+0000] {processor.py:157} INFO - Started process (PID=549) to work on /opt/airflow/dags/transform.py
[2023-06-16T00:44:54.837+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2023-06-16T00:44:54.839+0000] {logging_mixin.py:149} INFO - [2023-06-16T00:44:54.839+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2023-06-16T00:44:54.849+0000] {logging_mixin.py:149} INFO - [2023-06-16T00:44:54.845+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 12, in <module>
    "email_on_failaure": false,
NameError: name 'false' is not defined
[2023-06-16T00:44:54.850+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2023-06-16T00:44:54.992+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transform.py took 0.206 seconds
[2023-06-16T00:45:27.167+0000] {processor.py:157} INFO - Started process (PID=612) to work on /opt/airflow/dags/transform.py
[2023-06-16T00:45:27.302+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2023-06-16T00:45:27.305+0000] {logging_mixin.py:149} INFO - [2023-06-16T00:45:27.304+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2023-06-16T00:45:27.314+0000] {logging_mixin.py:149} INFO - [2023-06-16T00:45:27.311+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 12, in <module>
    "email_on_failaure": false,
NameError: name 'false' is not defined
[2023-06-16T00:45:27.316+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2023-06-16T00:45:27.490+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transform.py took 0.328 seconds
[2023-06-16T00:46:40.848+0000] {processor.py:157} INFO - Started process (PID=690) to work on /opt/airflow/dags/transform.py
[2023-06-16T00:46:40.956+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2023-06-16T00:46:40.957+0000] {logging_mixin.py:149} INFO - [2023-06-16T00:46:40.957+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2023-06-16T00:46:41.295+0000] {logging_mixin.py:149} INFO - [2023-06-16T00:46:41.076+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 12, in <module>
    "email_on_failaure": false,
NameError: name 'false' is not defined
[2023-06-16T00:46:41.297+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2023-06-16T00:46:41.635+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transform.py took 0.791 seconds
[2023-06-16T00:47:32.439+0000] {processor.py:157} INFO - Started process (PID=796) to work on /opt/airflow/dags/transform.py
[2023-06-16T00:47:32.493+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2023-06-16T00:47:32.497+0000] {logging_mixin.py:149} INFO - [2023-06-16T00:47:32.496+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2023-06-16T00:47:32.510+0000] {logging_mixin.py:149} INFO - [2023-06-16T00:47:32.505+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 12, in <module>
    "email_on_failaure": false,
NameError: name 'false' is not defined
[2023-06-16T00:47:32.512+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2023-06-16T00:47:32.768+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transform.py took 0.334 seconds
[2023-06-16T00:49:19.097+0000] {processor.py:157} INFO - Started process (PID=892) to work on /opt/airflow/dags/transform.py
[2023-06-16T00:49:19.218+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2023-06-16T00:49:19.222+0000] {logging_mixin.py:149} INFO - [2023-06-16T00:49:19.221+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2023-06-16T00:49:19.234+0000] {logging_mixin.py:149} INFO - [2023-06-16T00:49:19.231+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 12, in <module>
    "email_on_failaure": false,
NameError: name 'false' is not defined
[2023-06-16T00:49:19.235+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2023-06-16T00:49:19.341+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transform.py took 0.252 seconds
[2023-06-16T00:49:49.800+0000] {processor.py:157} INFO - Started process (PID=962) to work on /opt/airflow/dags/transform.py
[2023-06-16T00:49:49.801+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2023-06-16T00:49:49.803+0000] {logging_mixin.py:149} INFO - [2023-06-16T00:49:49.802+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2023-06-16T00:49:49.808+0000] {logging_mixin.py:149} INFO - [2023-06-16T00:49:49.806+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 12, in <module>
    "email_on_failaure": false,
NameError: name 'false' is not defined
[2023-06-16T00:49:49.808+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2023-06-16T00:49:50.019+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transform.py took 0.225 seconds
[2023-06-16T00:50:26.780+0000] {processor.py:157} INFO - Started process (PID=1036) to work on /opt/airflow/dags/transform.py
[2023-06-16T00:50:26.884+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2023-06-16T00:50:26.886+0000] {logging_mixin.py:149} INFO - [2023-06-16T00:50:26.886+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2023-06-16T00:50:26.896+0000] {logging_mixin.py:149} INFO - [2023-06-16T00:50:26.892+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 12, in <module>
    "email_on_failaure": false,
NameError: name 'false' is not defined
[2023-06-16T00:50:26.898+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2023-06-16T00:50:27.053+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transform.py took 0.279 seconds
[2023-06-16T00:51:02.808+0000] {processor.py:157} INFO - Started process (PID=1104) to work on /opt/airflow/dags/transform.py
[2023-06-16T00:51:02.923+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2023-06-16T00:51:02.924+0000] {logging_mixin.py:149} INFO - [2023-06-16T00:51:02.924+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2023-06-16T00:51:02.929+0000] {logging_mixin.py:149} INFO - [2023-06-16T00:51:02.927+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 12, in <module>
    "email_on_failaure": false,
NameError: name 'false' is not defined
[2023-06-16T00:51:02.930+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2023-06-16T00:51:03.238+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transform.py took 0.435 seconds
[2023-06-16T00:52:20.544+0000] {processor.py:157} INFO - Started process (PID=1185) to work on /opt/airflow/dags/transform.py
[2023-06-16T00:52:20.666+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2023-06-16T00:52:20.669+0000] {logging_mixin.py:149} INFO - [2023-06-16T00:52:20.668+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2023-06-16T00:52:20.784+0000] {logging_mixin.py:149} INFO - [2023-06-16T00:52:20.779+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 12, in <module>
    "email_on_failaure": false,
NameError: name 'false' is not defined
[2023-06-16T00:52:20.786+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2023-06-16T00:52:21.001+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transform.py took 0.468 seconds
[2023-06-16T00:58:52.196+0000] {processor.py:157} INFO - Started process (PID=121) to work on /opt/airflow/dags/transform.py
[2023-06-16T00:58:52.465+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2023-06-16T00:58:52.469+0000] {logging_mixin.py:149} INFO - [2023-06-16T00:58:52.468+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2023-06-16T00:58:54.441+0000] {logging_mixin.py:149} INFO - [2023-06-16T00:58:53.307+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 12, in <module>
    "email_on_failaure": false,
NameError: name 'false' is not defined
[2023-06-16T00:58:54.442+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2023-06-16T00:58:54.579+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transform.py took 2.397 seconds
[2023-06-16T01:02:24.702+0000] {processor.py:157} INFO - Started process (PID=241) to work on /opt/airflow/dags/transform.py
[2023-06-16T01:02:24.745+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2023-06-16T01:02:24.746+0000] {logging_mixin.py:149} INFO - [2023-06-16T01:02:24.746+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2023-06-16T01:02:24.750+0000] {logging_mixin.py:149} INFO - [2023-06-16T01:02:24.749+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 12, in <module>
    "email_on_failaure": false,
NameError: name 'false' is not defined
[2023-06-16T01:02:24.751+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2023-06-16T01:02:24.815+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transform.py took 0.118 seconds
[2023-06-16T01:02:55.653+0000] {processor.py:157} INFO - Started process (PID=306) to work on /opt/airflow/dags/transform.py
[2023-06-16T01:02:55.654+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2023-06-16T01:02:55.655+0000] {logging_mixin.py:149} INFO - [2023-06-16T01:02:55.655+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2023-06-16T01:02:55.658+0000] {logging_mixin.py:149} INFO - [2023-06-16T01:02:55.657+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 12, in <module>
    "email_on_failaure": false,
NameError: name 'false' is not defined
[2023-06-16T01:02:55.658+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2023-06-16T01:02:55.809+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transform.py took 0.160 seconds
[2023-06-16T01:03:27.251+0000] {processor.py:157} INFO - Started process (PID=377) to work on /opt/airflow/dags/transform.py
[2023-06-16T01:03:27.277+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2023-06-16T01:03:27.279+0000] {logging_mixin.py:149} INFO - [2023-06-16T01:03:27.278+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2023-06-16T01:03:27.285+0000] {logging_mixin.py:149} INFO - [2023-06-16T01:03:27.283+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 12, in <module>
    "email_on_failaure": false,
NameError: name 'false' is not defined
[2023-06-16T01:03:27.286+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2023-06-16T01:03:27.342+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transform.py took 0.100 seconds
[2023-06-16T01:03:57.891+0000] {processor.py:157} INFO - Started process (PID=445) to work on /opt/airflow/dags/transform.py
[2023-06-16T01:03:57.892+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2023-06-16T01:03:57.893+0000] {logging_mixin.py:149} INFO - [2023-06-16T01:03:57.893+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2023-06-16T01:03:57.898+0000] {logging_mixin.py:149} INFO - [2023-06-16T01:03:57.896+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 12, in <module>
    "email_on_failaure": false,
NameError: name 'false' is not defined
[2023-06-16T01:03:57.898+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2023-06-16T01:03:57.950+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transform.py took 0.065 seconds
[2023-06-16T09:58:42.677+0000] {processor.py:157} INFO - Started process (PID=110) to work on /opt/airflow/dags/transform.py
[2023-06-16T09:58:42.775+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2023-06-16T09:58:42.778+0000] {logging_mixin.py:149} INFO - [2023-06-16T09:58:42.778+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2023-06-16T09:58:42.965+0000] {logging_mixin.py:149} INFO - [2023-06-16T09:58:42.851+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 12, in <module>
    "email_on_failaure": false,
NameError: name 'false' is not defined
[2023-06-16T09:58:42.966+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2023-06-16T09:58:43.191+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transform.py took 0.518 seconds
[2023-06-16T09:59:14.161+0000] {processor.py:157} INFO - Started process (PID=176) to work on /opt/airflow/dags/transform.py
[2023-06-16T09:59:14.190+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2023-06-16T09:59:14.190+0000] {logging_mixin.py:149} INFO - [2023-06-16T09:59:14.190+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2023-06-16T09:59:14.194+0000] {logging_mixin.py:149} INFO - [2023-06-16T09:59:14.193+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 12, in <module>
    "email_on_failaure": false,
NameError: name 'false' is not defined
[2023-06-16T09:59:14.194+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2023-06-16T09:59:14.272+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transform.py took 0.115 seconds
[2023-06-16T09:59:49.602+0000] {processor.py:157} INFO - Started process (PID=245) to work on /opt/airflow/dags/transform.py
[2023-06-16T09:59:49.711+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2023-06-16T09:59:49.713+0000] {logging_mixin.py:149} INFO - [2023-06-16T09:59:49.713+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2023-06-16T09:59:49.719+0000] {logging_mixin.py:149} INFO - [2023-06-16T09:59:49.717+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 12, in <module>
    "email_on_failaure": false,
NameError: name 'false' is not defined
[2023-06-16T09:59:49.721+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2023-06-16T09:59:49.827+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transform.py took 0.231 seconds
[2023-06-16T10:00:21.031+0000] {processor.py:157} INFO - Started process (PID=317) to work on /opt/airflow/dags/transform.py
[2023-06-16T10:00:21.032+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2023-06-16T10:00:21.032+0000] {logging_mixin.py:149} INFO - [2023-06-16T10:00:21.032+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2023-06-16T10:00:21.036+0000] {logging_mixin.py:149} INFO - [2023-06-16T10:00:21.034+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 12, in <module>
    "email_on_failaure": false,
NameError: name 'false' is not defined
[2023-06-16T10:00:21.036+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2023-06-16T10:00:21.105+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transform.py took 0.078 seconds
[2023-06-16T10:01:09.084+0000] {processor.py:157} INFO - Started process (PID=385) to work on /opt/airflow/dags/transform.py
[2023-06-16T10:01:09.205+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2023-06-16T10:01:09.207+0000] {logging_mixin.py:149} INFO - [2023-06-16T10:01:09.206+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2023-06-16T10:01:09.212+0000] {logging_mixin.py:149} INFO - [2023-06-16T10:01:09.209+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 12, in <module>
    "email_on_failaure": false,
NameError: name 'false' is not defined
[2023-06-16T10:01:09.212+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2023-06-16T10:01:09.546+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transform.py took 0.476 seconds
[2023-06-16T10:01:40.100+0000] {processor.py:157} INFO - Started process (PID=452) to work on /opt/airflow/dags/transform.py
[2023-06-16T10:01:40.142+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2023-06-16T10:01:40.143+0000] {logging_mixin.py:149} INFO - [2023-06-16T10:01:40.143+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2023-06-16T10:01:40.147+0000] {logging_mixin.py:149} INFO - [2023-06-16T10:01:40.145+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 12, in <module>
    "email_on_failaure": false,
NameError: name 'false' is not defined
[2023-06-16T10:01:40.147+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2023-06-16T10:01:40.245+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transform.py took 0.155 seconds
[2023-06-16T10:02:10.670+0000] {processor.py:157} INFO - Started process (PID=520) to work on /opt/airflow/dags/transform.py
[2023-06-16T10:02:10.717+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2023-06-16T10:02:10.718+0000] {logging_mixin.py:149} INFO - [2023-06-16T10:02:10.718+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2023-06-16T10:02:10.824+0000] {logging_mixin.py:149} INFO - [2023-06-16T10:02:10.723+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 12, in <module>
    "email_on_failaure": false,
NameError: name 'false' is not defined
[2023-06-16T10:02:10.825+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2023-06-16T10:02:10.930+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transform.py took 0.274 seconds
[2023-06-16T10:03:20.482+0000] {processor.py:157} INFO - Started process (PID=611) to work on /opt/airflow/dags/transform.py
[2023-06-16T10:03:20.612+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2023-06-16T10:03:20.616+0000] {logging_mixin.py:149} INFO - [2023-06-16T10:03:20.615+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2023-06-16T10:03:20.671+0000] {logging_mixin.py:149} INFO - [2023-06-16T10:03:20.621+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 12, in <module>
    "email_on_failaure": false,
NameError: name 'false' is not defined
[2023-06-16T10:03:20.673+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2023-06-16T10:03:21.010+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transform.py took 0.533 seconds
[2023-06-16T10:05:45.080+0000] {processor.py:157} INFO - Started process (PID=710) to work on /opt/airflow/dags/transform.py
[2023-06-16T10:05:45.145+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2023-06-16T10:05:45.148+0000] {logging_mixin.py:149} INFO - [2023-06-16T10:05:45.148+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2023-06-16T10:05:45.158+0000] {logging_mixin.py:149} INFO - [2023-06-16T10:05:45.154+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 12, in <module>
    "email_on_failaure": false,
NameError: name 'false' is not defined
[2023-06-16T10:05:45.159+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2023-06-16T10:05:45.680+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transform.py took 0.612 seconds
[2023-06-16T10:06:17.516+0000] {processor.py:157} INFO - Started process (PID=773) to work on /opt/airflow/dags/transform.py
[2023-06-16T10:06:17.517+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2023-06-16T10:06:17.519+0000] {logging_mixin.py:149} INFO - [2023-06-16T10:06:17.519+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2023-06-16T10:06:17.594+0000] {logging_mixin.py:149} INFO - [2023-06-16T10:06:17.569+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 12, in <module>
    "email_on_failaure": false,
NameError: name 'false' is not defined
[2023-06-16T10:06:17.595+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2023-06-16T10:06:17.716+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transform.py took 0.208 seconds
[2023-06-16T10:06:48.018+0000] {processor.py:157} INFO - Started process (PID=841) to work on /opt/airflow/dags/transform.py
[2023-06-16T10:06:48.019+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2023-06-16T10:06:48.020+0000] {logging_mixin.py:149} INFO - [2023-06-16T10:06:48.020+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2023-06-16T10:06:48.023+0000] {logging_mixin.py:149} INFO - [2023-06-16T10:06:48.022+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 12, in <module>
    "email_on_failaure": false,
NameError: name 'false' is not defined
[2023-06-16T10:06:48.023+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2023-06-16T10:06:48.151+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transform.py took 0.139 seconds
[2023-06-16T10:08:51.189+0000] {processor.py:157} INFO - Started process (PID=936) to work on /opt/airflow/dags/transform.py
[2023-06-16T10:08:51.403+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2023-06-16T10:08:51.407+0000] {logging_mixin.py:149} INFO - [2023-06-16T10:08:51.406+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2023-06-16T10:08:51.673+0000] {logging_mixin.py:149} INFO - [2023-06-16T10:08:51.414+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 12, in <module>
    "email_on_failaure": false,
NameError: name 'false' is not defined
[2023-06-16T10:08:51.675+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2023-06-16T10:08:51.996+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transform.py took 0.813 seconds
[2023-06-16T10:14:13.820+0000] {processor.py:157} INFO - Started process (PID=112) to work on /opt/airflow/dags/transform.py
[2023-06-16T10:14:13.899+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2023-06-16T10:14:13.903+0000] {logging_mixin.py:149} INFO - [2023-06-16T10:14:13.902+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2023-06-16T10:14:14.059+0000] {logging_mixin.py:149} INFO - [2023-06-16T10:14:13.934+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 12, in <module>
    "email_on_failaure": false,
NameError: name 'false' is not defined
[2023-06-16T10:14:14.061+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2023-06-16T10:14:14.197+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transform.py took 0.382 seconds
[2023-06-16T10:14:44.424+0000] {processor.py:157} INFO - Started process (PID=177) to work on /opt/airflow/dags/transform.py
[2023-06-16T10:14:44.517+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2023-06-16T10:14:44.520+0000] {logging_mixin.py:149} INFO - [2023-06-16T10:14:44.519+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2023-06-16T10:14:44.531+0000] {logging_mixin.py:149} INFO - [2023-06-16T10:14:44.528+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 12, in <module>
    "email_on_failaure": false,
NameError: name 'false' is not defined
[2023-06-16T10:14:44.533+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2023-06-16T10:14:44.644+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transform.py took 0.225 seconds
[2023-06-16T10:15:15.208+0000] {processor.py:157} INFO - Started process (PID=238) to work on /opt/airflow/dags/transform.py
[2023-06-16T10:15:15.209+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2023-06-16T10:15:15.211+0000] {logging_mixin.py:149} INFO - [2023-06-16T10:15:15.210+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2023-06-16T10:15:15.216+0000] {logging_mixin.py:149} INFO - [2023-06-16T10:15:15.214+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 12, in <module>
    "email_on_failaure": false,
NameError: name 'false' is not defined
[2023-06-16T10:15:15.216+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2023-06-16T10:15:15.266+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transform.py took 0.063 seconds
[2023-06-16T10:15:46.138+0000] {processor.py:157} INFO - Started process (PID=308) to work on /opt/airflow/dags/transform.py
[2023-06-16T10:15:46.139+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2023-06-16T10:15:46.140+0000] {logging_mixin.py:149} INFO - [2023-06-16T10:15:46.140+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2023-06-16T10:15:46.144+0000] {logging_mixin.py:149} INFO - [2023-06-16T10:15:46.142+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 12, in <module>
    "email_on_failaure": false,
NameError: name 'false' is not defined
[2023-06-16T10:15:46.144+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2023-06-16T10:15:46.177+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transform.py took 0.043 seconds
[2023-06-16T10:16:16.455+0000] {processor.py:157} INFO - Started process (PID=376) to work on /opt/airflow/dags/transform.py
[2023-06-16T10:16:16.472+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2023-06-16T10:16:16.473+0000] {logging_mixin.py:149} INFO - [2023-06-16T10:16:16.473+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2023-06-16T10:16:16.476+0000] {logging_mixin.py:149} INFO - [2023-06-16T10:16:16.475+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 12, in <module>
    "email_on_failaure": false,
NameError: name 'false' is not defined
[2023-06-16T10:16:16.476+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2023-06-16T10:16:16.512+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transform.py took 0.061 seconds
[2023-06-16T10:16:47.745+0000] {processor.py:157} INFO - Started process (PID=444) to work on /opt/airflow/dags/transform.py
[2023-06-16T10:16:47.783+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2023-06-16T10:16:47.786+0000] {logging_mixin.py:149} INFO - [2023-06-16T10:16:47.785+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2023-06-16T10:16:47.796+0000] {logging_mixin.py:149} INFO - [2023-06-16T10:16:47.792+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 12, in <module>
    "email_on_failaure": false,
NameError: name 'false' is not defined
[2023-06-16T10:16:47.797+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2023-06-16T10:16:47.916+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transform.py took 0.176 seconds
[2023-06-16T10:17:18.881+0000] {processor.py:157} INFO - Started process (PID=513) to work on /opt/airflow/dags/transform.py
[2023-06-16T10:17:18.895+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2023-06-16T10:17:18.898+0000] {logging_mixin.py:149} INFO - [2023-06-16T10:17:18.897+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2023-06-16T10:17:18.905+0000] {logging_mixin.py:149} INFO - [2023-06-16T10:17:18.903+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 12, in <module>
    "email_on_failaure": false,
NameError: name 'false' is not defined
[2023-06-16T10:17:18.906+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2023-06-16T10:17:19.017+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transform.py took 0.141 seconds
[2023-06-16T10:18:19.975+0000] {processor.py:157} INFO - Started process (PID=602) to work on /opt/airflow/dags/transform.py
[2023-06-16T10:18:20.045+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2023-06-16T10:18:20.048+0000] {logging_mixin.py:149} INFO - [2023-06-16T10:18:20.047+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2023-06-16T10:18:20.057+0000] {logging_mixin.py:149} INFO - [2023-06-16T10:18:20.054+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 12, in <module>
    "email_on_failaure": false,
NameError: name 'false' is not defined
[2023-06-16T10:18:20.058+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2023-06-16T10:18:20.143+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transform.py took 0.172 seconds
[2023-06-16T10:18:50.317+0000] {processor.py:157} INFO - Started process (PID=670) to work on /opt/airflow/dags/transform.py
[2023-06-16T10:18:50.318+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2023-06-16T10:18:50.319+0000] {logging_mixin.py:149} INFO - [2023-06-16T10:18:50.319+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2023-06-16T10:18:50.322+0000] {logging_mixin.py:149} INFO - [2023-06-16T10:18:50.321+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 12, in <module>
    "email_on_failaure": false,
NameError: name 'false' is not defined
[2023-06-16T10:18:50.323+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2023-06-16T10:18:50.367+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transform.py took 0.054 seconds
[2023-06-16T10:19:20.875+0000] {processor.py:157} INFO - Started process (PID=738) to work on /opt/airflow/dags/transform.py
[2023-06-16T10:19:20.884+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/transform.py for tasks to queue
[2023-06-16T10:19:20.885+0000] {logging_mixin.py:149} INFO - [2023-06-16T10:19:20.885+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/transform.py
[2023-06-16T10:19:20.889+0000] {logging_mixin.py:149} INFO - [2023-06-16T10:19:20.888+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform.py", line 12, in <module>
    "email_on_failaure": false,
NameError: name 'false' is not defined
[2023-06-16T10:19:20.890+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/transform.py
[2023-06-16T10:19:20.930+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transform.py took 0.059 seconds
